# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 600

format = """
[ ](bg:15)\
$os\
$username\
[](fg:15 bg:24)\
$directory\
[](fg:24 bg:31)\
$git_branch\
$git_status\
[ ](fg:31 bg:none)
"""

right_format = """
$status\
$cmd_duration\
[](fg:31 bg:0)\
$golang\
[](fg:67 bg:31)\
$java\
[](fg:65 bg:67)\
$nodejs\
[](fg:220 bg:65)\
$python\
[](fg:124 bg:220)\
$ruby\
[](fg:24 bg:124)\
$time
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[c]
symbol = " "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[cmd_duration]
format = "[$duration]($style) "

[directory]
style = "fg:15 bg:24 bold"
format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"~/Code" = ""
"~/Documents" = "󰈙"
"~/Downloads" = ""
"~/Music" = ""
"~/Pictures" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
symbol = " "
style = "bg:30"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:31"
format = '[ $symbol $branch]($style)'

[git_status]
style = "bg:31"
format = '[$all_status( $ahead_behind) ]($style)'
# Specfic status flags
ahead = '( ⇡$count)'
behind = '( ⇣$count)'
conflicted = '( 󰞇$count)'
deleted = '( $count)'
modified = '( $count)'
staged = '( 󰮝$count)'
stashed = '( $count)'
untracked = '( 󰼈$count)'

[golang]
symbol = ""
style = "bg:31"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:67"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:65"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = false              # Disabled by default
style = "fg:0 bg:15"
format = '[$symbol ]($style)'

[os.symbols]
Alpaquita = ""
Alpine = ""
AlmaLinux = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
RockyLinux = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"

[python]
symbol = ""
style = "bg:220"
format = '[ $symbol ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:124"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:74"
format = '[ $symbol ($version) ]($style)'

[status]
disabled = false
symbol = "[✘](fg:red)"
success_symbol = "[](fg:green)"
format = '[$symbol( $common_meaning$signal_name$maybe_int)]($style) '

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:24"
format = '[  $time ]($style)'

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:15 fg:0"
style_root = "bg:15"
format = '[$user ]($style)'
disabled = true
